export const HMOVIES = [
  'The Christmas Secret (aka Flight of the Reindeer)',
  'Santa Jr.',
  'A Christmas Visitor',
  'A Carol Christmas',
  'A Boyfriend for Christmas',
  'Eve’s Christmas',
  'Single Santa Seeks Mrs. Claus',
  'Angel in the Family',
  'Silver Bells',
  'Meet the Santas',
  'The Christmas Card',
  'What I Did for Love',
  'A Grandpa for Christmas',
  'All I Want for Christmas',
  'Our First Christmas',
  'The Most Wonderful Time of the Year',
  'The Christmas Choir',
  'Moonlight and Mistletoe',
  'A Dog Named Christmas',
  'Mrs. Miracle',
  'Christmas in Canaan',
  'The Three Gifts',
  'The Night Before the Night Before Christmas',
  'The Town Christmas Forgot',
  'Call Me Mrs. Miracle',
  'November Christmas',
  'The Santa Suit',
  'Farewell Mr. Kringle',
  'Gift of the Magi',
  'The Santa Incident',
  'An Old Fashioned Christmas',
  'Three Wise Women',
  'Battle of the Bulbs',
  'Love’s Christmas Journey',
  'Mistletoe Over Manhattan',
  'Lucky Christmas',
  'Cancel Christmas',
  'A Christmas Wedding Tail',
  'The Case for Christmas',
  'A Christmas Wish',
  'Jingle All the Way',
  'Trading Christmas',
  'Holiday Engagement',
  'A Princess for Christmas',
  'Annie Claus is Coming to Town',
  'The Christmas Pageant',
  'Christmas Comes Home to Canaan',
  'Christmas Magic',
  'Christmas Song',
  'The Wishing Tree',
  'Matchmaker Santa',
  'It’s Christmas, Carol!',
  'Jingle & Bell’s Christmas Star',
  'Hitched for the Holidays',
  'A Bride for Christmas',
  'The Christmas Heart',
  'Come Dance with Me',
  'Help for the Holidays',
  'Baby’s First Christmas',
  'Pete’s Christmas',
  'Snow Bride',
  'A Very Merry Mix-Up',
  'The Christmas Ornament',
  'Catch a Christmas Star',
  'Window Wonderland',
  'Fir Crazy',
  'Let it Snow',
  'The Christmas Spirit',
  'Santa Switch',
  'Hats Off to Christmas!',
  'Finding Christmas',
  'Christmas with Tucker',
  'The Nine Lives of Christmas',
  'One Starry Christmas',
  'A Royal Christmas',
  'Northpole',
  'Christmas Under Wraps',
  'Christmas at Cartwright’s',
  'Angels and Ornaments',
  'A Cookie Cutter Christmas',
  'The Christmas Shepherd',
  'One Christmas Eve',
  'Mr. Miracle',
  'Best Christmas Party Ever',
  'The Christmas Parade',
  'Sign, Sealed, Delivered for Christmas',
  'Merry Matrimony',
  'Crown for Christmas',
  'A Christmas Detour',
  'Family for Christmas',
  '‘Tis the Season for Love',
  'Ice Sculpture Christmas',
  'I’m Not Ready for Christmas',
  'Christmas Incorporated',
  'Northpole: Open for Christmas',
  'Once Upon a Holiday',
  '12 Gifts of Christmas',
  'Angel of Christmas',
  'Just in Time for Christmas',
  'On the Twelfth Day of Christmas',
  'A Christmas Melody',
  'Christmas Land',
  'The Christmas Note',
  'Magic Stocking',
  'Dashing Through the Snow',
  'Christmas in Homestead',
  'A Wish for Christmas',
  'The Mistletoe Promise',
  'Every Christmas Has a Story',
  'Christmas Cookies',
  'My Christmas Dream',
  'A December Bride',
  'Broadcasting Christmas',
  'The Christmas List',
  'A Heavenly Christmas',
  'Journey Back to Christmas',
  'A Dream of Christmas',
  'A Nutcracker Christmas',
  'Looks Like Christmas',
  'A Love You Like Christmas',
  'My Christmas Love',
  'Sleigh Bells Ring',
  'When Calls the Heart Christmas',
  'Love Always, Santa',
  'Finding Father Christmas',
  'Operation Christmas',
  'I’ll be Home for Christmas',
  'Hearts for Christmas',
  'Sound of Christmas',
  'A Christmas to Remember',
  'Christmas Next Door',
  'Finding Santa',
  'The Christmas Train',
  'Switched for Christmas',
  'Christmas in Evergreen',
  'Christmas at Holly Lodge',
  'Christmas Encore',
  'Christmas Homecoming',
  'The Mistletoe Inn',
  'The Sweetest Christmas',
  'A Bramble House Christmas',
  'Christmas Getaway',
  'Christmas Connection',
  'A Joyous Christmas',
  'Christmas in Angel Falls',
  'A Song for Christmas',
  'Christmas in the Air',
  'A Rose for Christmas',
  'Marry Me at Christmas',
  'Christmas Festival of Ice',
  'Miss Christmas',
  'Enchanted Christmas',
  'Coming Home for Christmas',
  'A Gift to Remember',
  'With Love, Christmas',
  'The Christmas Cottage',
  'Sharing Christmas',
  'When Calls the Heart: The Christmas Wishing Tree',
  'The Perfect Christmas Present',
  'Engaging Father Christmas',
  'Magical Christmas Ornaments',
  'Karen Kingsbury’s Maggie’s Christmas Miracle',
  'Romance at Reindeer Lodge',
  'Rocky Mountain Christmas',
  'Christmas at Pemberley Manor',
  'Pride, Prejudice, and Mistletoe',
  'Christmas at Graceland',
  'Christmas at the Palace',
  'A Shoe Addict’s Christmas',
  'Christmas on Honeysuckle Lane',
  'Mingle All the Way',
  'A Majestic Christmas',
  'Entertaining Christmas',
  'A Gingerbread Romance',
  'Christmas in Love',
  'Christmas Made to Order',
  'Christmas Bells are Ringing',
  'Jingle Around the Clock',
  'A Veteran’s Christmas',
  'Welcome to Christmas',
  'A Godwink Christmas',
  'Christmas in Evergreen: Letters to Santa',
  'Reunited at Christmas',
  'A Christmas for the Books',
  'Christmas at Grand Valley',
  'Memories of Christmas',
  'Christmas Joy',
  'Road to Christmas',
  'It’s Christmas Eve',
  'Christmas Everlasting',
  'Homegrown Christmas',
  'When Calls the Heart: The Greatest Christmas Blessing',
  'Marrying Father Christmas',
  'Return to Christmas Creek',
  'Last Vermont Christmas',
  'Hope at Christmas',
  'Christmas Wonderland',
  'Once Upon a Christmas Miracle',
  'Time for Me to Come Home for Christmas',
  'Small Town Christmas',
  'Christmas in Montana',
  'A Homecoming for the Holidays',
  'Our Christmas Love Song',
  'A Family Christmas Gift',
  'Christmas Scavenger Hunt',
  'Picture a Perfect Christmas',
  'Christmas at Dollywood',
  'Christmas in Rome',
  'Christmas Town',
  'Christmas at the Plaza',
  'Sense, Sensibility & Snowmen',
  'Double Holiday',
  'The Christmas Club',
  'Merry & Bright',
  'A Christmas Love Story',
  'Christmas in Evergreen: Tidings of Joy',
  'Christmas in Louisiana',
  'Angel Falls: A Novel Holiday',
  'Christmas Wishes & Mistletoe Kisses',
  'The Mistletoe Secret',
  'Christmas Under the Stars',
  'Write Before Christmas',
  'Christmas at Graceland: Home for the Holidays',
  'A Gift to Cherish',
  'A Christmas Duet',
  'Check Inn to Christmas',
  'Holiday Date',
  'A Cheerful Christmas',
  'It’s Beginning to Look a Lot Like Christmas',
  'When Calls the Heart: Home for Christmas',
  'Christmas Camp',
  'A Merry Christmas Match',
  'Nostalgic Christmas',
  'Two Turtle Doves',
  'A Blue Ridge Mountain Christmas',
  'Holiday for Heroes',
  'A Christmas Miracle',
  'A Godwink Christmas: Meant for Love',
  'Holiday Hearts',
  'Time for You to Come Home for Christmas',
  'Christmas on My Mind',
  'Christmas in Evergreen: Bells Are Ringing',
  'Cross Country Christmas',
  'A Little Christmas Charm',
  'USS Christmas',
  'A Nashville Christmas Carol',
  'The Christmas House',
  'Deliver by Christmas',
  'Holly & Ivy',
  'Christmas Waltz',
  'Christmas in Vienna',
  'Christmas Comes Twice',
  'A Christmas Tree Grows in Colorado',
  'Christmas Carousel',
  'Love, Lights, Hanukkah!',
  'Project Christmas Wish',
  'A Glenbrooke Christmas (',
  'If I Only Had Christmas',
  'Christmas She Wrote',
  'Christmas by Starlight',
  'Five Star Christmas',
  'The Christmas Bow',
  'A Godwink Christmas: Second Changes, First Love',
  'Winter in Vail',
  'Love in Winterland',
  'Jingle Bell Bride',
  'Chateau Christmas',
  'One Royal Holiday',
  'On the 12th Date of Christmas',
  'Never Kiss a Man in a Christmas Sweater',
  'Christmas with the Darlings',
  'A Timeless Christmas',
  'Love & Gingerbread',
  'A Bright and Merry Christmas',
  'Christmas Tree Lane',
  'Cranberry Christmas',
  'The Christmas Ring',
  'Meet Me at Christmas',
  'The Christmas Doctor',
  'The Angel Tree',
  'Time for Us to Come Home for Christmas',
  'Swept Up By Christmas',
  'Christmas in the Rockies',
  'A New Year’s Resolution',
  'Christmas in Tahoe',
  'Christmas in Harmony',
  'You, Me & Christmas Trees',
  'Christmas at Castle Hart',
  'The Santa Stakeout',
  'Christmas CEO',
  'Gingerbread Miracle',
  'The Christmas Promise',
  'A Timeless Christmas',
  'Christmas in My Heart',
  'A Dickens of a Holiday',
  'A Very Merry Bridesmaid',
  'Our Christmas Journey',
  'Christmas Wishes & Mistletoe Kisses',
  'A Christmas Treasure',
  'The Christmas Contest',
  'Crashing Through the Snow',
  'Boyfriends of Christmas Past',
  'Coyote Creek Christmas',
  'Christmas Sail',
  'Open by Christmas',
  'My Christmas Family Tree',
  'A Holiday in Harlem',
  'Nantucket Noel',
  'A Christmas Together with You',
  'A Kiss Before Christmas',
  'The Nine Kittens of Christmas',
  'An Unexpected Christmas',
  'Making Spirits Bright',
  'Eight Gifts of Hanukkah',
  'Sister Swap: A Hometown Holiday',
  'A Royal Queens Christmas',
  'Sister Swap: Christmas in the City',
  'The Christmas House 2: Deck Those Halls',
  '’Tis the Season to be Merry',
  'Next Stop Christmas',
  'One December Night',
  'Debbie Macomber’s A Mrs. Miracle Christmas',
  'Five More Minutes',
  'Time for Them to Come Home for Christmas',
  'A Godwink Christmas: Miracle of Love',
  'Christmas for Keeps',
  'Noel Next Door',
  'We Wish You a Married Christmas',
  'A Kismet Christmas',
  'A Cozy Christmas Inn',
  'Jolly Good Christmas',
  'Ghosts of Christmas Always',
  'A Magical Christmas Village',
  'Lights, Camera, Christmas!',
  'All Saints Christmas',
  'In Merry Measure',
  'The Royal Nanny',
  'Christmas at the Golden Dragon',
  'Inventing the Christmas Prince',
  'Three Wise Men and a Baby',
  'When I Think of Christmas',
  'My Southern Family Christmas',
  '#Xmas',
  'A Royal Corgi Christmas',
  'A Tale of Two Christmases',
  'Haul Out the Holly',
  'A Christmas Cookie Catastrophe',
  'A Holiday Spectacular',
  'A Big Fat Family Christmas',
  'A Fabled Holiday',
  'Undercover Holiday',
  'The Most Colorful Time of the Year',
  'Christmas Class Reunion',
  'The Holiday Sitter',
  'Holiday Heritage',
  '‘Twas the Night Before Christmas',
  'Hanukkah on Rye',
  'We Need a Little Christmas',
  'Christmas Bedtime Stories',
  'A Maple Valley Christmas',
  'Our Italian Christmas Memories',
  'Long Lost Christmas',
  'Time for Him to Come Home for Christmas',
  'The Holiday Stocking',
  'The Gift of Peace',
  'Checkin’ It Twice',
  'Where Are You, Christmas?',
  'Under the Christmas Sky',
  'Christmas By Design',
  'Mystic Christmas',
  'Joyeux Noel',
  'Flipping for Christmas',
  'Never Been Chris’d',
  'The Santa Summit',
  'Everything Christmas',
  'Christmas Island',
  'A Heidelberg Holiday',
  'Navigating Christmas',
  'A Merry Scottish Christmas',
  'Holiday Hotline',
  'Catch Me If You Claus',
  'Letters to Santa',
  'Holiday Road',
  'Christmas in Notting Hill',
  'Haul Out the Holly: Lit Up',
  'Our Christmas Mural',
  'A Biltmore Christmas',
  'My Norwegian Holiday',
  'A Not So Royal Christmas',
  'Christmas with a Kiss (A Mahogany Presentation)',
  'Magic in Mistletoe',
  'Christmas on Cherry Lane',
  'Round and Round',
  'The Secret Gift of Christmas',
  'Sealed with a List',
  'Friends & Family Christmas',
  'Ms. Christmas Comes to Town',
  'My Christmas Guide',
  'Mystery on Mistletoe Lane',
  'A World Record Christmas',
  'A Season for Family',
  'Time for Her to Come Home at Christmas',
  'To All a Good Night',
  'Heaven Down Here',
  'Miracle in Bethlehem, PA (A Dayspring Movie)',
  'Falling Like Snowflakes',
  'A Very Vermont Christmas',
  'Rescuing Christmas',
  'Operation Nutcracker',
  'An Ice Palace Romance',
]

export const MOVIES = [
  "It's a Wonderful Life",
  'Home Alone',
  'A Christmas Story',
  'Elf',
  "National Lampoon's Christmas Vacation",
  'The Polar Express',
  'Die Hard',
  'The Nightmare Before Christmas',
  'Miracle on 34th Street',
  'How the Grinch Stole Christmas',
  'Scrooged',
  'The Santa Clause',
  'Love Actually',
  'White Christmas',
  'Bad Santa',
  'A Charlie Brown Christmas',
  'Rudolph the Red-Nosed Reindeer',
  'Frosty the Snowman',
  'The Muppet Christmas Carol',
  'Gremlins',
  'The Holiday',
  'Jingle All the Way',
  'Arthur Christmas',
  'The Family Stone',
  'Christmas with the Kranks',
  "The Bishop's Wife",
  'Holiday Inn',
  'The Ref',
  'The Year Without a Santa Claus',
  'Prancer',
  'The Little Drummer Boy',
  'Santa Claus: The Movie',
  'Jack Frost',
  'Ernest Saves Christmas',
  'The Christmas Shoes',
  'The Nativity Story',
  'A Christmas Carol',
  'The Snowman',
  'Babes in Toyland',
  "The Preacher's Wife",
  'Mixed Nuts',
  'One Magic Christmas',
  'The Best Man Holiday',
  'A Christmas Tale',
  'The Man Who Came to Dinner',
  'The Holly and the Ivy',
  'Remember the Night',
  'Christmas in Connecticut',
  'The Shop Around the Corner',
  'Meet Me in St. Louis',
  'The Lemon Drop Kid',
  "We're No Angels",
  'Bell, Book and Candle',
  'The Apartment',
  'A Christmas Carol',
  'Scrooge',
  'Black Christmas',
  'Silent Night, Deadly Night',
  'Rare Exports: A Christmas Tale',
  'Krampus',
  'The Family Man',
  'Surviving Christmas',
  'Fred Claus',
  'Four Christmases',
  'Deck the Halls',
  "I'll Be Home for Christmas",
  'The Santa Clause 2',
  'The Santa Clause 3: The Escape Clause',
  'Home Alone 2: Lost in New York',
  'Home Alone 3',
  'Home Alone 4: Taking Back the House',
  'Home Alone: The Holiday Heist',
  'A Christmas Prince',
  'The Princess Switch',
  'The Christmas Chronicles',
  'Klaus',
  'Jingle Jangle: A Christmas Journey',
  'Noelle',
  'Last Christmas',
  'Happiest Season',
  'A Bad Moms Christmas',
  'Office Christmas Party',
  'The Night Before',
  "Daddy's Home 2",
  'Love the Coopers',
  'A Very Harold & Kumar Christmas',
  'The Polar Express',
  'Arthur Christmas',
  'Rise of the Guardians',
  'The Star',
  'The Nutcracker and the Four Realms',
  'A Christmas Carol',
  'The Grinch',
  'The Man Who Invented Christmas',
]
